### PR TITLE
Add nordgedanken.ffnord as "UserDomain"

### PR DESCRIPTION
**Pull request by MTRNord**

### CODE REVIEW

**Comment by Tarnatos** [comment]
CC @rubo77 @sventhomsen

**Comment by sventhomsen** [comment]
We should  require AAAA-Records. 

@MTRNord: Please add AAAA-Record for "nordgedanken", please rebase on master

**Comment by MTRNord** [comment]
Kommt sobald der pi wieder läuft :)

**Comment by MTRNord** [comment]
Will make new PR if I have the needed Data :)

**Pull request closed without merging**
